package net.gudenau.discord.images.magick;

public final class Types{
    public static final long MagickSignature = 0xABACADABL;
    
    public static final int
        UndefinedException = 0,
        WarningException = 300,
        ResourceLimitWarning = 300,
        TypeWarning = 305,
        OptionWarning = 310,
        DelegateWarning = 315,
        MissingDelegateWarning = 320,
        CorruptImageWarning = 325,
        FileOpenWarning = 330,
        BlobWarning = 335,
        StreamWarning = 340,
        CacheWarning = 345,
        CoderWarning = 350,
        ModuleWarning = 355,
        DrawWarning = 360,
        ImageWarning = 365,
        XServerWarning = 380,
        MonitorWarning = 385,
        RegistryWarning = 390,
        ConfigureWarning = 395,
        ErrorException = 400,
        ResourceLimitError = 400,
        TypeError = 405,
        OptionError = 410,
        DelegateError = 415,
        MissingDelegateError = 420,
        CorruptImageError = 425,
        FileOpenError = 430,
        BlobError = 435,
        StreamError = 440,
        CacheError = 445,
        CoderError = 450,
        ModuleError = 455,
        DrawError = 460,
        ImageError = 465,
        XServerError = 480,
        MonitorError = 485,
        RegistryError = 490,
        ConfigureError = 495,
        FatalErrorException = 700,
        ResourceLimitFatalError = 700,
        TypeFatalError = 705,
        OptionFatalError = 710,
        DelegateFatalError = 715,
        MissingDelegateFatalError = 720,
        CorruptImageFatalError = 725,
        FileOpenFatalError = 730,
        BlobFatalError = 735,
        StreamFatalError = 740,
        CacheFatalError = 745,
        CoderFatalError = 750,
        ModuleFatalError = 755,
        DrawFatalError = 760,
        ImageFatalError = 765,
        XServerFatalError = 780,
        MonitorFatalError = 785,
        RegistryFatalError = 790,
        ConfigureFatalError = 795;
    
    public static final int
        CharPixel = 0,
        ShortPixel = 1,
        IntegerPixel = 2,
        LongPixel = 3,
        FloatPixel = 4,
        DoublePixel = 5;
}
